### ISSUE TITLE
Can't resolve 'React' in module.

### ISSUE THREAD

**Issue by Magellol** [gragland/react-perfect-image#1]
Hey, I was about to use your component for one of my projects, although when I import it, webpack complains about not finding `'React'`.

Here's the complete webpack output:

```
ERROR in ./~/react-perfect-image/dist/image.js
Module not found: Error: Can't resolve 'React' in '...node_modules/react-perfect-image/dist'
 @ ./~/react-perfect-image/dist/image.js 1:82-98
 @ ./src/components/App.js
 @ ./src/client.js
```

I took a look at `dist/image.js` and I found out that the react library got capitalized.
![screen shot 2017-03-10 at 2 30 57 pm](https://cloud.githubusercontent.com/assets/3819093/23810108/350d27aa-059e-11e7-8c8e-183b6d703814.png)

Not sure if that's the _real_ cause but replacing all of these occurrences by `react` instead of `React`, it fixed it.

Maybe that is introduced somewhere around [here](https://github.com/gragland/react-perfect-image/blob/master/webpack.config.js#L17).

I'm using webpack 2, if that helps :)

**Comment by gragland** [comment]
Thanks for reporting this issue and the helpful debug details! Just pushed a fix so update to the latest version on npm and you should be good to go. It was in fact due to the Webpack externals config that you linked to.
